
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jul 05 18:39:08 CEST 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LTE = 34;
  public static final int LBRACKET = 46;
  public static final int CHAR = 53;
  public static final int CONST = 7;
  public static final int LPAREN = 44;
  public static final int CONTINUE = 17;
  public static final int RPAREN = 45;
  public static final int INSTANCEOF = 21;
  public static final int SEMICOLON = 39;
  public static final int AND = 36;
  public static final int LT = 35;
  public static final int RECORD = 20;
  public static final int OR = 37;
  public static final int BOOL = 52;
  public static final int COMMA = 41;
  public static final int CLASS = 4;
  public static final int INC = 22;
  public static final int DIV = 27;
  public static final int ASSIGN = 38;
  public static final int IF = 8;
  public static final int THIS = 18;
  public static final int EXP = 29;
  public static final int DOT = 43;
  public static final int VARARGS = 42;
  public static final int EOF = 0;
  public static final int RETURN = 14;
  public static final int RBRACKET = 47;
  public static final int SUPER = 19;
  public static final int NEW = 11;
  public static final int error = 1;
  public static final int MUL = 26;
  public static final int ADD = 24;
  public static final int NUMBER = 51;
  public static final int MOD = 28;
  public static final int NEQ = 31;
  public static final int IDENT = 50;
  public static final int BREAK = 3;
  public static final int VOID = 15;
  public static final int EQ = 30;
  public static final int GTE = 32;
  public static final int COLON = 40;
  public static final int LBRACE = 48;
  public static final int ELSE = 6;
  public static final int ENUM = 5;
  public static final int READ = 13;
  public static final int WHILE = 10;
  public static final int RBRACE = 49;
  public static final int EXTENDS = 16;
  public static final int PROG = 2;
  public static final int DEC = 23;
  public static final int GT = 33;
  public static final int SUB = 25;
  public static final int PRINT = 12;
  public static final int DO = 9;
}

