
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Jul 16 23:41:47 CEST 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LTE = 32;
  public static final int LBRACKET = 44;
  public static final int CHAR = 51;
  public static final int CONST = 7;
  public static final int LPAREN = 42;
  public static final int CONTINUE = 17;
  public static final int RPAREN = 43;
  public static final int INSTANCEOF = 19;
  public static final int SEMICOLON = 37;
  public static final int AND = 34;
  public static final int LT = 33;
  public static final int RECORD = 18;
  public static final int OR = 35;
  public static final int BOOL = 50;
  public static final int COMMA = 39;
  public static final int CLASS = 4;
  public static final int INC = 20;
  public static final int DIV = 25;
  public static final int ASSIGN = 36;
  public static final int IF = 8;
  public static final int EXP = 27;
  public static final int DOT = 41;
  public static final int VARARGS = 40;
  public static final int EOF = 0;
  public static final int RETURN = 14;
  public static final int RBRACKET = 45;
  public static final int NEW = 11;
  public static final int error = 1;
  public static final int MUL = 24;
  public static final int ADD = 22;
  public static final int NUMBER = 49;
  public static final int MOD = 26;
  public static final int NEQ = 29;
  public static final int IDENT = 48;
  public static final int BREAK = 3;
  public static final int VOID = 15;
  public static final int EQ = 28;
  public static final int GTE = 30;
  public static final int COLON = 38;
  public static final int LBRACE = 46;
  public static final int ELSE = 6;
  public static final int ENUM = 5;
  public static final int READ = 13;
  public static final int WHILE = 10;
  public static final int RBRACE = 47;
  public static final int EXTENDS = 16;
  public static final int PROG = 2;
  public static final int DEC = 21;
  public static final int GT = 31;
  public static final int SUB = 23;
  public static final int PRINT = 12;
  public static final int DO = 9;
}

